CREATE USER app_user WITH PASSWORD 'app_password';
GRANT CONNECT ON DATABASE documents TO app_user;
GRANT USAGE, CREATE ON SCHEMA public TO app_user;

CREATE TABLE IF NOT EXISTS documents (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    text TEXT NOT NULL,
    rubrics JSONB NOT NULL,
    created_date TIMESTAMPTZ NOT NULL
);

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO app_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO app_user;
